// src/partials/MainNav/MainNav.tsx
"use client";
import React, { useState, ReactElement } from "react";
import NavDropdown from "@/partials/NavDropdown/NavDropdown";
import NavLink from "@/partials/NavLink/NavLink";
import Auth from "../Auth/Auth";
import styles from "./MainNav.module.scss";
import Link from "next/link";

/**
 * MainNav - The main navigation component of the application.
 * It utilizes Bootstrap classes for responsiveness and flexbox for alignment.
 */
export default function MainNav(): ReactElement {
  const [isCollapsed, setIsCollapsed] = useState(true);

  return (
    <div className="d-flex justify-content-around bg-primary shadow navbar navbar-expand-md">
      <Link className="navbar-brand" href={"/"}>
        <img
          src="/images/deejPotterLogo.png"
          alt="The Deej Potter logo."
          height={64}
          width={64}
        />
      </Link>
      <nav className={` ${styles.navbar}`}>
        {/* Toggler button for smaller screens */}
        <button
          className="navbar-toggler"
          type="button"
          onClick={() => setIsCollapsed(!isCollapsed)}
        >
          <span className="oi oi-menu" />
        </button>

        {/* Collapsible menu items */}
        <div
          className={`${isCollapsed ? "collapse" : ""} navbar-collapse ${styles.navbarCollapse}`}
        >
          <NavDropdown
            btnLabel="Websites"
            indexHref="/websites"
            navLinks={[{ href: "/websites/deejpotter", label: "Deejpotter" }]}
          />
          <NavDropdown
            btnLabel="Apps"
            indexHref="/apps"
            navLinks={[{ href: "/apps/todo-app", label: "Todo App" }]}
          />
          <NavLink href="/about" label="About" />
          <NavLink href="/contact" label="Contact" />
        </div>
      </nav>

      {/* Auth component aligned to the right */}
      <Auth />
    </div>
  );
}

// AngularFiles/src/app/shared/partials/main-nav/main-nav.component.ts
import {Component} from '@angular/core';
import {dropdownAnimation} from '../../utils/animations';

@Component({
  selector: 'app-main-nav',
  templateUrl: './main-nav.component.html',
  styleUrls: ['./main-nav.component.scss'],
  animations: [dropdownAnimation()],
})
export class MainNavComponent {
  isMenuCollapsed = true;
  isFunDropdownOpen = false;
  isWebsitesDropdownOpen = false;
  isGamesDropdownOpen = false;

  toggleNavMenu(): void {
    this.isMenuCollapsed = !this.isMenuCollapsed;
  }

  closeNavMenu(): void {
    this.isMenuCollapsed = true;
  }

  showDropdown(dropdown: string): void {
    this.isFunDropdownOpen = dropdown === 'fun';
    this.isWebsitesDropdownOpen = dropdown === 'websites';
    this.isGamesDropdownOpen = dropdown === 'games';
  }

  hideDropdowns(): void {
    this.isFunDropdownOpen = false;
    this.isWebsitesDropdownOpen = false;
    this.isGamesDropdownOpen = false;
  }
}

<nav class="navbar navbar-expand-md bg-primary shadow">
  <div class="container">
    <a class="navbar-brand" routerLink="/">
      <img ngSrc="/assets/images/deejPotterLogo.svg" alt="The Deej Potter logo." height="128" width="128">
    </a>
    <button class="navbar-toggler" type="button" (click)="toggleNavMenu()" [class.collapsed]="isMenuCollapsed">
      <span class="oi oi-menu"></span>
    </button>
    <div [ngbCollapse]="isMenuCollapsed" class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav nav-fill">

        <li class="nav-item dropdown" [class.show]="isFunDropdownOpen" (mouseenter)="showDropdown('fun')" (mouseleave)="hideDropdowns()" (click)="closeNavMenu()">
          <a class="nav-link dropdown-toggle" role="button" routerLink="/fun" aria-haspopup="true" aria-expanded="false">Fun stuff</a>
          <div class="dropdown-menu" [@dropdownAnimation]="isFunDropdownOpen ? 'visible' : 'hidden'">
            <a class="dropdown-item" routerLink="/fun/todo" (click)="closeNavMenu()">Todo List</a>
          </div>
        </li>

        <li class="nav-item dropdown" [class.show]="isGamesDropdownOpen" (mouseenter)="showDropdown('games')" (mouseleave)="hideDropdowns()" (click)="closeNavMenu()">
          <a class="nav-link dropdown-toggle" role="button" routerLink="/games" aria-haspopup="true" aria-expanded="false">Games</a>
          <div class="dropdown-menu" [@dropdownAnimation]="isGamesDropdownOpen ? 'visible' : 'hidden'">
            <a class="dropdown-item" routerLink="/games/basegame" (click)="closeNavMenu()">Base Game</a>
          </div>
        </li>

        <li class="nav-item dropdown" [class.show]="isWebsitesDropdownOpen" (mouseenter)="showDropdown('websites')" (mouseleave)="hideDropdowns()" (click)="closeNavMenu()">
          <a class="nav-link dropdown-toggle" role="button" routerLink="/websites" aria-haspopup="true" aria-expanded="false">Websites
          </a>
          <div class="dropdown-menu" [@dropdownAnimation]="isWebsitesDropdownOpen ? 'visible' : 'hidden'">
            <a class="dropdown-item" routerLink="/websites" (click)="closeNavMenu()">Websites</a>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link" routerLink="/about" (click)="closeNavMenu()">About me</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" routerLink="/contact" (click)="closeNavMenu()">Contact me</a>
        </li>

        <app-auth></app-auth>

      </ul>
    </div>
  </div>
</nav>
