// src/app/shared/partials/gradient-hero-section/gradient-hero-section.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-gradient-hero-section',
  templateUrl: './gradient-hero-section.component.html',
  styleUrls: ['./gradient-hero-section.component.scss']
})
export class GradientHeroSectionComponent {
  @Input() title: string = "";
  @Input() subtitle: string = "";
  @Input() gradientFrom: string = "primary";
  @Input() gradientTo: string = "light";
  @Input() textColour: string = "dark";
}

<section class="{{gradientFrom}}-{{gradientTo}}-gradient text-{{textColour}} py-5">
  <div class="container text-center">
    <h1 class="display-1">{{title}}</h1>
    <p class="lead">{{subtitle}}</p>
  </div>
</section>

// src/templates/GradientHeroSection/GradientHeroSection.tsx
import {ReactElement} from "react";
import {GradientHeroSectionParams} from "@/templates/GradientHeroSection/GradientHeroSectionParams";

export default function GradientHeroSection({gradientFrom, gradientTo, subtitle, textColour, title}: GradientHeroSectionParams): ReactElement {
  return (<section className={`${gradientFrom}-${gradientTo}-gradient text-${textColour} py-5`}>
    <div className="container text-center">
      <h1 className="display-1">{title}</h1>
      <p className="lead">{subtitle}</p>
    </div>
  </section>)
}
