// src/app/shared/partials/auth/auth.component.ts
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {AuthService} from 'src/app/shared/services/auth.service';
import {ToastrService} from "ngx-toastr";

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.scss'],
})
export class AuthComponent implements OnInit {

  constructor(public authService: AuthService, private router: Router, private toastr: ToastrService) {
  }

  ngOnInit(): void {
  }

  onLogin(): void {
    this.authService.login().subscribe({
      next: () => {
        this.toastr.success('Logged in successfully', 'Success');
      },
      error: (error: Error) => {
        console.error('Login failed:', error.message);
      }
    });
  }

  onSignup(): void {
    this.authService.signUp().subscribe({
      next: () => {
        this.toastr.success('Signed up successfully', 'Success');
      },
      error: (error: Error) => {
        console.error('Signup failed:', error.message);
      }
    });
  }

  onLogout(): void {
    this.authService.logout().subscribe({
      next: (result) => {
        this.router.navigate(['/']);
        this.toastr.success('Logged out successfully', 'Success');
      },
      error: (error) => {
        console.error('Logout error:', error);
        this.toastr.error('Logout failed', 'Error');
      },
    });
  }

}

<div *ngIf="!authService.isAuthenticated()" class="navbar-nav">
  <div class="nav-item">
    <button (click)="onLogin()" class="btn btn-sm btn-outline-secondary shadow mx-1">Login</button>
    <button (click)="onSignup()" class="btn btn-sm btn-outline-secondary shadow">Sign up</button>
  </div>
</div>

<div *ngIf="authService.isAuthenticated()" class="nav-item">
  <div class="d-flex align-items-center">
    <img ngxGravatar [email]="currentUser?.email || ''" [size]="32" class="rounded-circle mx-1" alt="The logged in user's Gravatar.">
    <button (click)="toastrTest()" class="btn btn-sm btn-outline-danger shadow">Test</button>
    <button (click)="onLogout()" class="btn btn-sm btn-outline-danger shadow">Logout</button>
  </div>
</div>

// src/partials/navbar/Auth.tsx
"use client";
import React from "react";
import { useAuth } from "@/contexts/AuthContext";
import Gravatar from "./Gravatar";

const Auth = () => {
	const { user, login, signup, logout } = useAuth();

	return (
		<div className="navbar-nav">
			{user ? (
				<div className="nav-item d-flex align-items-center">
					<Gravatar email={user.email} className="rounded-circle mx-1 shadow" />
					<button
						onClick={logout}
						className="btn btn-sm btn-outline-danger shadow"
					>
						Logout
					</button>
				</div>
			) : (
				<div className="nav-item">
					<button
						onClick={login}
						className="btn btn-sm btn-outline-secondary shadow mx-1"
					>
						Login
					</button>
					<button
						onClick={signup}
						className="btn btn-sm btn-outline-secondary shadow"
					>
						Sign up
					</button>
				</div>
			)}
		</div>
	);
};

export default Auth;
