// AngularFiles/src/app/pages/games/basic-bases/basic-bases.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-basic-bases',
  templateUrl: './basic-bases.component.html',
  styleUrls: ['./basic-bases.component.scss']
})
export class BasicBasesComponent {

}

<div class="game-container">
  <iframe src="../../../../assets/games/baserGame/index.html" frameborder="0"></iframe>
</div>

// src/app/projects/games/basic-bases/page.tsx
import { generatePageMetadata } from "@/app/metadata";

export const metadata = generatePageMetadata(
  "Basic Bases",
  "Play Basic Bases, a browser game by Deej Potter.",
  "/projects/games/basic-bases"
);

import { ReactElement } from "react";

export default function BasicBases(): ReactElement {
  return (
    <div className="gameContainer">
      <iframe src="/basicBases/index.html" frameBorder="0"></iframe>
    </div>
  );
}
