// src/templates/BasicSection/BasicSection.tsx
import { ReactElement } from "react";

export default function BasicSection(props: any): ReactElement {
  return (
    <section
      className={`bg-${props.backgroundColour} text-${props.textColour} py-5`}
    >
      <div className="container">
        <h2>{props.heading}</h2>
        <p>{props.paragraph}</p>
      </div>
    </section>
  );
}

// src/app/shared/templates/sections/basic-section/basic-section.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-basic-section',
  templateUrl: './basic-section.component.html',
  styleUrls: ['./basic-section.component.scss']
})
export class BasicSectionComponent {
  @Input() heading: string = "";
  @Input() paragraph: string = "";
  @Input() backgroundColour: string = "";
  @Input() textColour: string = "";
}
