// src/partials/MainNav/MainNav.tsx
"use client";
import React, { useState, ReactElement } from "react";
import NavDropdown from "@/partials/NavDropdown/NavDropdown";
import NavLink from "@/partials/NavLink/NavLink";
import Auth from "../Auth/Auth";
import styles from "./MainNav.module.scss";
import Link from "next/link";

/**
 * MainNav - The main navigation component of the application.
 * It utilizes Bootstrap classes for responsiveness and flexbox for alignment.
 */
export default function MainNav(): ReactElement {
  const [isCollapsed, setIsCollapsed] = useState(true);

  return (
    <div className="d-flex justify-content-around bg-primary shadow navbar navbar-expand-md">
      <Link className="navbar-brand" href={"/"}>
        <img
          src="/images/deejPotterLogo.png"
          alt="The Deej Potter logo."
          height={64}
          width={64}
        />
      </Link>
      <nav className={` ${styles.navbar}`}>
        {/* Toggler button for smaller screens */}
        <button
          className="navbar-toggler"
          type="button"
          onClick={() => setIsCollapsed(!isCollapsed)}
        >
          <span className="oi oi-menu" />
        </button>

        {/* Collapsible menu items */}
        <div
          className={`${isCollapsed ? "collapse" : ""} navbar-collapse ${styles.navbarCollapse}`}
        >
          <NavDropdown
            btnLabel="Websites"
            indexHref="/websites"
            navLinks={[{ href: "/websites/deejpotter", label: "Deejpotter" }]}
          />
          <NavDropdown
            btnLabel="Apps"
            indexHref="/apps"
            navLinks={[{ href: "/apps/todo-app", label: "Todo App" }]}
          />
          <NavLink href="/about" label="About" />
          <NavLink href="/contact" label="Contact" />
        </div>
      </nav>

      {/* Auth component aligned to the right */}
      <Auth />
    </div>
  );
}

// src/app/partials/main-nav/main-nav.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-main-nav',
  templateUrl: './main-nav.component.html',
  styleUrls: ['./main-nav.component.scss']
})

export class MainNavComponent {
  isMenuCollapsed: boolean = true;

  public ToggleNavMenu() {
    this.isMenuCollapsed = !this.isMenuCollapsed;
  }

  public OpenNavMenu() {
    this.isMenuCollapsed = false;
  }

  public CloseNavMenu() {
    this.isMenuCollapsed = true;
  }
}

<nav class="navbar navbar-expand-md bg-primary shadow mb-3">
  <!-- Navbar brand -->
  <div class="container">
    <a class="navbar-brand" routerLink="">
      <img src="../../../assets/images/deejPotterLogo.svg" alt="The Deej Potter logo.">
    </a>

    <!-- Toggle Button -->
    <button (click)="ToggleNavMenu()" class="navbar-toggler" type="button">
      <span class="oi oi-menu"></span>
    </button>

    <!-- Nav -->
    <div [ngbCollapse]="isMenuCollapsed" class="collapse navbar-collapse justify-content-end">
      <div class="navbar-nav nav-fill">
        <div class="nav-item">
          <a class="nav-link" routerLink="about" (click)="CloseNavMenu()">
            <span class="oi oi-person" aria-hidden="true"></span> About me
          </a>
        </div>
        <div class="nav-item">
          <a class="nav-link" routerLink="portfolio" (click)="CloseNavMenu()">
            <span class="oi oi-list-rich" aria-hidden="true"></span> Portfolio
          </a>
        </div>
        <div class="nav-item">
          <a class="nav-link" routerLink="contact" (click)="CloseNavMenu()">
            <span class="oi oi-phone" aria-hidden="true"></span> Contact me
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>
